# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openconfig-interfaces.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='openconfig-interfaces.proto',
  package='openconfig_interfaces',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1bopenconfig-interfaces.proto\x12\x15openconfig_interfaces\"\x88\x07\n\nInterfaces\x12>\n\tinterface\x18\x01 \x03(\x0b\x32+.openconfig_interfaces.Interfaces.Interface\x1a\xb9\x06\n\tInterface\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x42\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x32.openconfig_interfaces.Interfaces.Interface.Config\x12\x46\n\x08holdtime\x18\x03 \x01(\x0b\x32\x34.openconfig_interfaces.Interfaces.Interface.HoldTime\x12P\n\rsubinterfaces\x18\x04 \x01(\x0b\x32\x39.openconfig_interfaces.Interfaces.Interface.Subinterfaces\x1a\x94\x01\n\x06\x43onfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x32\n\x04type\x18\x02 \x01(\x0e\x32$.openconfig_interfaces.InterfaceType\x12\x0b\n\x03mtu\x18\x03 \x01(\x04\x12\x15\n\rloopback_mode\x18\x04 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x06 \x01(\x08\x1a{\n\x08HoldTime\x12K\n\x06\x63onfig\x18\x01 \x01(\x0b\x32;.openconfig_interfaces.Interfaces.Interface.HoldTime.Config\x1a\"\n\x06\x43onfig\x12\n\n\x02up\x18\x01 \x01(\x04\x12\x0c\n\x04\x64own\x18\x02 \x01(\x04\x1a\xab\x02\n\rSubinterfaces\x12\\\n\x0csubinterface\x18\x02 \x03(\x0b\x32\x46.openconfig_interfaces.Interfaces.Interface.Subinterfaces.Subinterface\x1a\xbb\x01\n\x0cSubinterface\x12\r\n\x05index\x18\x01 \x01(\x04\x12]\n\x06\x63onfig\x18\x02 \x01(\x0b\x32M.openconfig_interfaces.Interfaces.Interface.Subinterfaces.Subinterface.Config\x1a=\n\x06\x43onfig\x12\r\n\x05index\x18\x01 \x01(\x04\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x03 \x01(\x08*8\n\rInterfaceType\x12\x12\n\x0e\x65thernetCsmcsd\x10\x00\x12\x13\n\x0fsoftwareLooback\x10\x01\x62\x06proto3'
)

_INTERFACETYPE = _descriptor.EnumDescriptor(
  name='InterfaceType',
  full_name='openconfig_interfaces.InterfaceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ethernetCsmcsd', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='softwareLooback', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=961,
  serialized_end=1017,
)
_sym_db.RegisterEnumDescriptor(_INTERFACETYPE)

InterfaceType = enum_type_wrapper.EnumTypeWrapper(_INTERFACETYPE)
ethernetCsmcsd = 0
softwareLooback = 1



_INTERFACES_INTERFACE_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='openconfig_interfaces.Interfaces.Interface.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='openconfig_interfaces.Interfaces.Interface.Config.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='openconfig_interfaces.Interfaces.Interface.Config.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mtu', full_name='openconfig_interfaces.Interfaces.Interface.Config.mtu', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loopback_mode', full_name='openconfig_interfaces.Interfaces.Interface.Config.loopback_mode', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='openconfig_interfaces.Interfaces.Interface.Config.description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='openconfig_interfaces.Interfaces.Interface.Config.enabled', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=532,
)

_INTERFACES_INTERFACE_HOLDTIME_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='openconfig_interfaces.Interfaces.Interface.HoldTime.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='up', full_name='openconfig_interfaces.Interfaces.Interface.HoldTime.Config.up', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='down', full_name='openconfig_interfaces.Interfaces.Interface.HoldTime.Config.down', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=623,
  serialized_end=657,
)

_INTERFACES_INTERFACE_HOLDTIME = _descriptor.Descriptor(
  name='HoldTime',
  full_name='openconfig_interfaces.Interfaces.Interface.HoldTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='openconfig_interfaces.Interfaces.Interface.HoldTime.config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INTERFACES_INTERFACE_HOLDTIME_CONFIG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=534,
  serialized_end=657,
)

_INTERFACES_INTERFACE_SUBINTERFACES_SUBINTERFACE_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='openconfig_interfaces.Interfaces.Interface.Subinterfaces.Subinterface.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='openconfig_interfaces.Interfaces.Interface.Subinterfaces.Subinterface.Config.index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='openconfig_interfaces.Interfaces.Interface.Subinterfaces.Subinterface.Config.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='openconfig_interfaces.Interfaces.Interface.Subinterfaces.Subinterface.Config.enabled', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=898,
  serialized_end=959,
)

_INTERFACES_INTERFACE_SUBINTERFACES_SUBINTERFACE = _descriptor.Descriptor(
  name='Subinterface',
  full_name='openconfig_interfaces.Interfaces.Interface.Subinterfaces.Subinterface',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='openconfig_interfaces.Interfaces.Interface.Subinterfaces.Subinterface.index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='openconfig_interfaces.Interfaces.Interface.Subinterfaces.Subinterface.config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INTERFACES_INTERFACE_SUBINTERFACES_SUBINTERFACE_CONFIG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=772,
  serialized_end=959,
)

_INTERFACES_INTERFACE_SUBINTERFACES = _descriptor.Descriptor(
  name='Subinterfaces',
  full_name='openconfig_interfaces.Interfaces.Interface.Subinterfaces',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subinterface', full_name='openconfig_interfaces.Interfaces.Interface.Subinterfaces.subinterface', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INTERFACES_INTERFACE_SUBINTERFACES_SUBINTERFACE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=660,
  serialized_end=959,
)

_INTERFACES_INTERFACE = _descriptor.Descriptor(
  name='Interface',
  full_name='openconfig_interfaces.Interfaces.Interface',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='openconfig_interfaces.Interfaces.Interface.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='openconfig_interfaces.Interfaces.Interface.config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='holdtime', full_name='openconfig_interfaces.Interfaces.Interface.holdtime', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subinterfaces', full_name='openconfig_interfaces.Interfaces.Interface.subinterfaces', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INTERFACES_INTERFACE_CONFIG, _INTERFACES_INTERFACE_HOLDTIME, _INTERFACES_INTERFACE_SUBINTERFACES, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=959,
)

_INTERFACES = _descriptor.Descriptor(
  name='Interfaces',
  full_name='openconfig_interfaces.Interfaces',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface', full_name='openconfig_interfaces.Interfaces.interface', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INTERFACES_INTERFACE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=959,
)

_INTERFACES_INTERFACE_CONFIG.fields_by_name['type'].enum_type = _INTERFACETYPE
_INTERFACES_INTERFACE_CONFIG.containing_type = _INTERFACES_INTERFACE
_INTERFACES_INTERFACE_HOLDTIME_CONFIG.containing_type = _INTERFACES_INTERFACE_HOLDTIME
_INTERFACES_INTERFACE_HOLDTIME.fields_by_name['config'].message_type = _INTERFACES_INTERFACE_HOLDTIME_CONFIG
_INTERFACES_INTERFACE_HOLDTIME.containing_type = _INTERFACES_INTERFACE
_INTERFACES_INTERFACE_SUBINTERFACES_SUBINTERFACE_CONFIG.containing_type = _INTERFACES_INTERFACE_SUBINTERFACES_SUBINTERFACE
_INTERFACES_INTERFACE_SUBINTERFACES_SUBINTERFACE.fields_by_name['config'].message_type = _INTERFACES_INTERFACE_SUBINTERFACES_SUBINTERFACE_CONFIG
_INTERFACES_INTERFACE_SUBINTERFACES_SUBINTERFACE.containing_type = _INTERFACES_INTERFACE_SUBINTERFACES
_INTERFACES_INTERFACE_SUBINTERFACES.fields_by_name['subinterface'].message_type = _INTERFACES_INTERFACE_SUBINTERFACES_SUBINTERFACE
_INTERFACES_INTERFACE_SUBINTERFACES.containing_type = _INTERFACES_INTERFACE
_INTERFACES_INTERFACE.fields_by_name['config'].message_type = _INTERFACES_INTERFACE_CONFIG
_INTERFACES_INTERFACE.fields_by_name['holdtime'].message_type = _INTERFACES_INTERFACE_HOLDTIME
_INTERFACES_INTERFACE.fields_by_name['subinterfaces'].message_type = _INTERFACES_INTERFACE_SUBINTERFACES
_INTERFACES_INTERFACE.containing_type = _INTERFACES
_INTERFACES.fields_by_name['interface'].message_type = _INTERFACES_INTERFACE
DESCRIPTOR.message_types_by_name['Interfaces'] = _INTERFACES
DESCRIPTOR.enum_types_by_name['InterfaceType'] = _INTERFACETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Interfaces = _reflection.GeneratedProtocolMessageType('Interfaces', (_message.Message,), {

  'Interface' : _reflection.GeneratedProtocolMessageType('Interface', (_message.Message,), {

    'Config' : _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
      'DESCRIPTOR' : _INTERFACES_INTERFACE_CONFIG,
      '__module__' : 'openconfig_interfaces_pb2'
      # @@protoc_insertion_point(class_scope:openconfig_interfaces.Interfaces.Interface.Config)
      })
    ,

    'HoldTime' : _reflection.GeneratedProtocolMessageType('HoldTime', (_message.Message,), {

      'Config' : _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
        'DESCRIPTOR' : _INTERFACES_INTERFACE_HOLDTIME_CONFIG,
        '__module__' : 'openconfig_interfaces_pb2'
        # @@protoc_insertion_point(class_scope:openconfig_interfaces.Interfaces.Interface.HoldTime.Config)
        })
      ,
      'DESCRIPTOR' : _INTERFACES_INTERFACE_HOLDTIME,
      '__module__' : 'openconfig_interfaces_pb2'
      # @@protoc_insertion_point(class_scope:openconfig_interfaces.Interfaces.Interface.HoldTime)
      })
    ,

    'Subinterfaces' : _reflection.GeneratedProtocolMessageType('Subinterfaces', (_message.Message,), {

      'Subinterface' : _reflection.GeneratedProtocolMessageType('Subinterface', (_message.Message,), {

        'Config' : _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
          'DESCRIPTOR' : _INTERFACES_INTERFACE_SUBINTERFACES_SUBINTERFACE_CONFIG,
          '__module__' : 'openconfig_interfaces_pb2'
          # @@protoc_insertion_point(class_scope:openconfig_interfaces.Interfaces.Interface.Subinterfaces.Subinterface.Config)
          })
        ,
        'DESCRIPTOR' : _INTERFACES_INTERFACE_SUBINTERFACES_SUBINTERFACE,
        '__module__' : 'openconfig_interfaces_pb2'
        # @@protoc_insertion_point(class_scope:openconfig_interfaces.Interfaces.Interface.Subinterfaces.Subinterface)
        })
      ,
      'DESCRIPTOR' : _INTERFACES_INTERFACE_SUBINTERFACES,
      '__module__' : 'openconfig_interfaces_pb2'
      # @@protoc_insertion_point(class_scope:openconfig_interfaces.Interfaces.Interface.Subinterfaces)
      })
    ,
    'DESCRIPTOR' : _INTERFACES_INTERFACE,
    '__module__' : 'openconfig_interfaces_pb2'
    # @@protoc_insertion_point(class_scope:openconfig_interfaces.Interfaces.Interface)
    })
  ,
  'DESCRIPTOR' : _INTERFACES,
  '__module__' : 'openconfig_interfaces_pb2'
  # @@protoc_insertion_point(class_scope:openconfig_interfaces.Interfaces)
  })
_sym_db.RegisterMessage(Interfaces)
_sym_db.RegisterMessage(Interfaces.Interface)
_sym_db.RegisterMessage(Interfaces.Interface.Config)
_sym_db.RegisterMessage(Interfaces.Interface.HoldTime)
_sym_db.RegisterMessage(Interfaces.Interface.HoldTime.Config)
_sym_db.RegisterMessage(Interfaces.Interface.Subinterfaces)
_sym_db.RegisterMessage(Interfaces.Interface.Subinterfaces.Subinterface)
_sym_db.RegisterMessage(Interfaces.Interface.Subinterfaces.Subinterface.Config)


# @@protoc_insertion_point(module_scope)
